### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by 10203901427** [neolee/wop#104]
![DJFIK80760X (N`A)WBE4NO](https://user-images.githubusercontent.com/71881365/100091895-35571580-2e90-11eb-8b18-3718d1f1e20b.png)
老师，例题里面能self.base >self.high,请问为什么这里不能等于呢？

**Comment by neolee** [comment]
大小比较时要用 `==`，一个 `=` 是赋值，不是比较操作符。
