### ISSUE TITLE
__next__ 方法下的 for in

### ISSUE THREAD

**Issue by 10203901427** [neolee/wop#105]
![55fb6b5e135738a60764e0a15ec1bae](https://user-images.githubusercontent.com/71881365/100111476-1913a280-2ea9-11eb-94b5-3e768fc95f66.png)
老师，我运行了以后就成了找奇数，好像for in没起作用，是for in 在__next__方法下用不了吗？还是哪里错了呀

**Comment by neolee** [comment]
`__next__()` 方法里的逻辑写错了，你可以看看我在这个问题里的回答 #101 ，按照里面的思路再想想。

p.s. 仔细看你目前的代码，你目前的逻辑是：对 2~b 之间的整数 a 循环执行，用 a 去除 self.base，除尽了就 break（然后函数就结束了，返回一个 None），除不尽就返回 self.base，这样的话，无论除不除得尽，你的循环都只会执行一次就退出了，这肯定是不对的吧？所以我建议把“判断 n 是否素数”这个功能单独写成一个函数，然后按照我上面给你的 #101 问题里提示的思路去做。
