### ISSUE TITLE
关于 sort 方法对 key 使用函数的问题

### ISSUE THREAD

**Issue by Bamgod** [neolee/wop#106]
老师，想详细请教一下之前想您询问的关于如下片段1可以实现但片段2会报错的问题

片段1
`person1 = {'name':'Neo','age':30,'height':175}
person2 = {'name':'Trinity','age':29,'height':169}
person3 = {'name':'Norpheus','age':43,'height':180}

data = [person1,person2,person3]

#sort by name:
data.sort(key = lambda item: item['name'])
print(data)`

片段2
`person1 = {'name':'Neo','age':30,'height':175}
person2 = {'name':'Trinity','age':29,'height':169}
person3 = {'name':'Norpheus','age':43,'height':180}

data = [person1,person2,person3]

def getkey(x):
	lambda item: item['x']

#sort by name:
data.sort(key = getkey(name))
print(data)`

谢谢您！

**Comment by neolee** [comment]
1. 首先你贴代码的方式没整对，具体好好学习下 https://github.com/neolee/wop-ecnu-pub/wiki 上的内容。

2. 关于函数。

在第七讲“函数再探 · 续”中我们讲过，函数也是一种数据类型，比如下面的代码：

```python
def add(a, b):
    return a + b
```

这段代码定义了一个函数对象，它需要两个输入参数（`a` 和 `b`），返回这两个输入参数相加之和，并且创建了一个变量 `add` 指向这个函数对象。

下面的代码效果完全相同：

```python
add = lambda a, b: a+b
```

上面这段代码通过 `lambda` 关键字创建了一个函数对象，它需要两个输入参数（`a` 和 `b`），返回这两个输入参数相加之和，然后通过一个普通的赋值语句把这个函数对象赋值给变量 `add`（也就是把 `add` 指向该函数对象）。

3. 关于 `lst.sort()` 和 `sorted()` 函数里的 `key` 参数

无论是 list 对象的 `sort()` 方法还是独立的 `sorted()` 函数，都有一个 `keyword` 参数叫 `key`，调用时这个参数的值必须是一个函数对象，且这个函数对象有且只有一个输入参数 `x`，`sort()` 和 `sorted()` 会用列表里的每一个元素作为输入参数来调用这个函数对象，然后用返回的结果来进行排序。

4. 最后回到你的问题，你的目标其实是：设计一个函数来返回不同的函数对象，分别用于上述 `key` 参数。下面是正确的实现方法，你可以尝试理解——以目前课程进度来说略微超前，等下周我们讲完函数式思想会更好理解一些。

```python
person1 = {'name':'Neo','age':30,'height':175}
person2 = {'name':'Trinity','age':29,'height':169}
person3 = {'name':'Morpheus','age':43,'height':180}

data = [person1,person2,person3]

def key_by_field(field):
    return lambda x: x[field]

print(sorted(data, key=key_by_field('name')))
print(sorted(data, key=key_by_field('age')))
print(sorted(data, key=key_by_field('height')))
print(sorted(data, key=key_by_field('height'), reverse=True))
```

关键是记住：`sorted` 的 `key` 参数必须是一个函数，且这个函数是有且只有一个输入参数的。

**Comment by Bamgod** [comment]
好的 谢谢老师！
