### ISSUE TITLE
为什么提示 Assertion is always true？

### ISSUE THREAD

**Issue by dishangti** [neolee/wop#111]
```python
class TreeNode:
    def __init__(self, name = None, level = None, parent = None):
        assert(name, str)
        assert(level, str)
        assert(parent, TreeNode)

        self.name = name
        self.level = level
        self.parent = parent
        self.children = []
        if parent:
            parent.add_child(self)

    def add_child(self, node):
        assert(node, TreeNode)
        node.parent = self
        self.children.append(node)
        
def new_country(name):
    return TreeNode(name, 'country', None)

def add_city(name, senior):
    return TreeNode(name, 'city', senior)

def add_area(name, senior):
    return TreeNode(name, 'area', senior)

def add_province(name, senior):
    return TreeNode(name, 'province', senior)

def add_county(name, senior):
    return TreeNode(name, 'county', senior)

def add_town(name, senior):
    return TreeNode(name, 'town', senior)

if __name__ == '__main__':
    CN = new_country('China')

    MG = add_province('Menggu', CN)

    SC = add_province('Cichuan', CN)
    SC_CD = add_city('Chengdu', SC)
    SC_CQ = add_city('Chongqing', SC)
    SC_PZH = add_city('Panzhihua', SC)
    SC_MY = add_city('Mianyang', SC)
```
只贴了一部分但是可以运行，但是运行时候会显示
c:\Users\dst\Desktop\LocationTree - 副本.py:3: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(name, str)
c:\Users\dst\Desktop\LocationTree - 副本.py:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(level, str)
c:\Users\dst\Desktop\LocationTree - 副本.py:5: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(parent, TreeNode)
c:\Users\dst\Desktop\LocationTree - 副本.py:15: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(node, TreeNode)

**Comment by neolee** [comment]
你搞错了 `assert` 的用法。

`assert` 是一个保留字开始的特殊语句，不是一个函数，`assert` 后面是一个表达式，根据这个表达式求值的结果来决定是继续执行还是中止程序。

你写的 `assert(name, str)` 中用来验证的表达式就是 `(name, str)`，这是一个非空的 tuple，它当然代表 `True`，其他几句同理。

你想做的是验证 `name` 是不是 `str` 类型，这需要借助内置函数 `isinstance()` 来实现，所以你应该写 `assert isinstance(name, str)` 才对，正如我在课上举例的那样。
