### ISSUE TITLE
tree 一节的 find 函数

### ISSUE THREAD

**Issue by CHANCYstone** [neolee/wop#118]
老师你好！

find函数第一开始参考了老师ppt中的办法
![image](https://user-images.githubusercontent.com/71212547/114289217-aea27e00-9aa8-11eb-966a-df2e04f004a2.png)
  ```
  def find(self, name):
        if self.name == name:
            return self
        
        else:
            if self.children and len(self.children):
                for child in self.children:
                    return child.find(name)
```
发现只能find 每一级树枝的第一枝的名字
![image](https://user-images.githubusercontent.com/71212547/114289257-0d67f780-9aa9-11eb-97df-15cbe6369414.png)
例如，只能找到Theria 而找不到Yinothria。
后来找到老师给的case

```
def find(self, name):
        if self.name == name:
            return self       
        for node in self.children:
            t = node.find(name)
            if t:
                return t
```
自己操作了一下发现，我的问题的核心是：
`if t :`
这段代码
所以我在想对于tree的递归那节的ppt中，
能不能写为这样
![image](https://user-images.githubusercontent.com/71212547/114289420-4c4a7d00-9aaa-11eb-8a12-22b2f8a8fd3d.png)
不知道自己想的可不可以，烦请老师指正。

**Comment by neolee** [comment]
你的版本 `if f(treenode):` 是不行的，我给出的那个版本的关键就是把递归调用和返回分开，这叫“延迟返回”，是为了保证递归执行完整的一种技术。你可以自己再思考一下。
