### ISSUE TITLE
安装homebrew遇到问题

### ISSUE THREAD

**Issue by Paloma333** [neolee/wop#132]
老师您好！我在安装homebrew过程中显示Failed to connect to raw.githubusercontent.com port 443: Connection refused，请问该如何解决？

**Comment by andyhuang18** [comment]
你好，抱歉这么迟回复你。如果没有配置加速器的情况下，直接按照 `homebrew` 官网的方法安装会报错，这个有关 `port 443` 的错误是因为无法访问 Github 导致的。你可以采取如下三种方法：
1. 配置代理，具体方法可以查阅网络上相关资料。
2. 借由国内镜像访问安装，比较简单的参考[知乎链接](https://zhuanlan.zhihu.com/p/111014448)。在命令行中输入`/bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"`即可。但是由于作者较长时间未更新，此方案的 `homebrew` 不排除以后会有小问题～
3. 借由国内镜像访问安装，[清华大学开源软件站](https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/)提供了最新的 `homebrew` 下载，按照步骤即可完成。

`homebrew` 是macOS的包管理工具，安装 `homebrew` 后安装 `git` 更加方便。

😄 有任何问题都可以提出来，非常欢迎！

**Comment by Paloma333** [comment]
收到！谢谢老师详细的解答！！！
---- Replied Message ----
| From | ***@***.***> |
| Date | 09/16/2023 19:54 |
| To | neolee/wop ***@***.***> |
| Cc | Paloma333 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [neolee/wop] 安装homebrew遇到问题 (Issue #132) |

你好，抱歉这么迟回复你。如果没有配置加速器的情况下，直接按照 homebrew 官网的方法安装会报错，这个有关 port 443 的错误是因为无法访问 Github 导致的。你可以采取如下三种方法：

配置代理，具体方法可以查阅网络上相关资料。
借由国内镜像访问安装，比较简单的参考知乎链接。在命令行中输入/bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"即可。但是由于作者较长时间未更新，此方案的 homebrew 不排除以后会有小问题～
借由国内镜像访问安装，清华大学开源软件站提供了最新的 homebrew 下载，按照步骤即可完成。

homebrew 是macOS的包管理工具，安装 homebrew 后安装 git 更加方便。

有任何问题都可以提出来，非常欢迎！

**Comment by lily052815501532021** [comment]
老师你好，我在安装homebrew时候，按照步骤输入：/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"时候，经常404，后面我把https:后面的部分即👇
https://raw.githubusercontent.com/Homebrew/install/master/install
复制到网站的时候也是404，是不是说明输入错了吗？

**Comment by neolee** [comment]
> 老师你好，我在安装homebrew时候，按照步骤输入：/usr/bin/ruby -e "$(curl -fsSL [https://raw.githubusercontent.com/Homebrew/install/master/install)"时候，经常404，后面我把https:后面的部分即👇](https://raw.githubusercontent.com/Homebrew/install/master/install)%22%E6%97%B6%E5%80%99%EF%BC%8C%E7%BB%8F%E5%B8%B8404%EF%BC%8C%E5%90%8E%E9%9D%A2%E6%88%91%E6%8A%8Ahttps:%E5%90%8E%E9%9D%A2%E7%9A%84%E9%83%A8%E5%88%86%E5%8D%B3%F0%9F%91%87)
> https://raw.githubusercontent.com/Homebrew/install/master/install
> 复制到网站的时候也是404，是不是说明输入错了吗？

Homebrew 的安装脚本地址变了，我需要更新相关文档，感谢指出~

你可以到 Homebrew 官网照着做： https://brew.sh

或者尝试国内镜像例如： https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/
