### ISSUE TITLE
关于父子类继承的问题

### ISSUE THREAD

**Issue by fengzhihuixue** [neolee/wop#93]
如果说自己创建的Bot的init函数和think函数和run函数都需要修改，那这时候父类是不就没有用了

**Comment by neolee** [comment]
即使如此，父类仍然有用：

1. 父类定义了这些函数的“接口（*interface*）”，也就是说这些函数的名字、输入参数和返回值类型都是父类定义好的，子类必须遵循，子类改的只是函数的实现而已；
2. 在很多时候，子类对这些函数的实现中，可以通过 `super()` 来调用父类的函数实现，避免重复代码。

p.s. 如果你设计了一个父类，而它的子类几乎都需要自定义所有函数的实现，父类只起到一个“接口统一定义”的作用，在不少编程语言中（如 C++、Java）对这种父类有专门的名词，叫“抽象父类（*abstract class*）”或者就叫“接口（*interface*）”。

p.p.s 在你们目前的学习阶段，还是应该努力寻找一些共性功能，完整封装到父类，然后子类舒服的用它就好了。这个练习很有价值。

**Comment by fengzhihuixue** [comment]
好的好的，谢谢老师
