### ISSUE TITLE
Visual Studio Code 运行的问题

### ISSUE THREAD

**Issue by fengzhihuixue** [neolee/wop#94]
![image](https://user-images.githubusercontent.com/71932925/97025479-b3bb5180-158a-11eb-92b8-7f367d16be28.png)
我在jupyter lab里就可以运行，在Visual Studio Code里就报错，请问这是为什么。。。

**Comment by neolee** [comment]
把你的 .py 源文件作为附件贴到这里，我来试试。

**Comment by fengzhihuixue** [comment]
不好意思哈老师。。我昨天可能瞎搞
今天就好使了
