### ISSUE TITLE
程序出现乱码

### ISSUE THREAD

**Issue by fengzhihuixue** [neolee/wop#96]
![image](https://user-images.githubusercontent.com/71932925/97098175-ee210d80-16b4-11eb-81d7-fd60497b5bf9.png)

![image](https://user-images.githubusercontent.com/71932925/97098180-02650a80-16b5-11eb-8056-89eb376bd33a.png)
![image](https://user-images.githubusercontent.com/71932925/97098183-0ee96300-16b5-11eb-9576-7fe95f1c97c4.png)
就是那个[0m

**Comment by neolee** [comment]
比较像是用来给文字上色的控制码，你使用了 termcolor 对吧？你在什么环境运行代码的？

**Comment by fengzhihuixue** [comment]
对，用的 Visual Studio Code

**Comment by neolee** [comment]
使用 ConEmu 或者 Windows Terminal 运行你的源程序试试。

**Comment by fengzhihuixue** [comment]
在conemu里就没有了，谢谢老师

**Comment by neolee** [comment]
嗯嗯，这是因为有的环境下，VS Code 自带的那个终端命令行界面会有配置上的问题，会导致 TermColor 无法正常工作。
