### ISSUE TITLE
第三方库引用失败

### ISSUE THREAD

**Issue by ashenimage** [neolee/wop#97]
按照指令用pip安装了termcolor
PS C:\Users\86150\Desktop\python稿子> pip install termcolor
Requirement already satisfied: termcolor in c:\users\86150\appdata\local\programs\python\python37\lib\site-packages (1.1.0)

但仍出现以下问题：
Unable to import 'termcolor'

![QQ截图20201026203129](https://user-images.githubusercontent.com/73476962/97176501-0174cb80-17d0-11eb-8f52-ffe604b9306c.png)

请问是否是路径的问题

**Comment by neolee** [comment]
你在命令行执行 `termcolor` 是啥意思呀？

**Comment by ashenimage** [comment]
额，就是问题中那张图想让您看到我在terminal里确实有安装，但是检错的时候它还是告诉我无法引入，这是problem一栏的报错截图，请您过目
![QQ截图20201026203129](https://user-images.githubusercontent.com/73476962/97248648-2fdcc000-183d-11eb-8360-7ea0ed1e8eef.png)

**Comment by neolee** [comment]
那个报错可以无视，有时候是 VS Code 的误判，只要你用 `python bot.py` 运行正常就没问题。

**Comment by ashenimage** [comment]
python里可以运行了，多谢老师
