### ISSUE TITLE
循环结构问题

### ISSUE THREAD

**Issue by fengzhihuixue** [neolee/wop#98]
![Y}5LQ ZNFN ~ U$FY7K$H](https://user-images.githubusercontent.com/71932925/97198084-625ccd80-17e9-11eb-8ff8-bb89834f1601.png)
最后的continue为什么没有发挥作用啊。。。。，就是并没有跳入循环

**Comment by neolee** [comment]
你最后那个 continue 是想干啥的？它已经在循环体最后一行了，等于没用呀。

**Comment by fengzhihuixue** [comment]
但是我现在的循环也不好使啊，当我输入之后他运行，运行完他就直接跳到结束语了，并没有继续循环。。。。。

**Comment by neolee** [comment]
那你要研究下：什么情况下会继续循环，你输入的内容是会走到继续循环的分支，还是会走到结束的分支。

从你的代码看，只有 `try` 下面的代码块出错，进入 `except` 下面的代码块，才会走 `continue` 继续循环。那么，你看看 `try` 下面的两行会出错么？

**Comment by fengzhihuixue** [comment]
我试过了，try下面的可以出错，而且可以进入循环，现在是我正确的输入，不进入except，运行完之后并没有循环，而是直接跳出。。
重复的我再想办法改改。。。。

**Comment by neolee** [comment]
> 我试过了，try下面的可以出错，而且可以进入循环，现在是我正确的输入，不进入except，运行完之后并没有循环，而是直接跳出

这个有啥问题么？目的不就是“出错了就提示然后循环再输入、正确了就挑出循环继续”吗？
